name: Build IPA (manual Flutter install)

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔥 Installer Flutter manuellement (pas de Subosito)
      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.27.1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Check versions
        run: |
          flutter --version
          dart --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
